languageCode = "en"
languageName = "🇬🇧 English"
languageDirection = "ltr"
weight = 1

title = "My portfolio"
copyright = "Alix ANNERAUD. Built with [Hugo](https://gohugo.io/) and [Congo](https://jpanther.github.io/congo/) theme. [GitHub](https://github.com/AlixANNERAUD/Web_site)"

[params]
dateFormat = "2 January 2006"
description = "Alix ANNERAUD's portfolio"

[params.author]
name = "Alix ANNERAUD"
image = "Images/Alix.png"
headline = "21-year old student in computer science."
links = [
  { email = "mailto:alix@anneraud.fr" },
  { github = "https://github.com/AlixANNERAUD" },
  { linkedin = "https://www.linkedin.com/in/alix-anneraud/" },
]
